# Generated by Django 4.2.7 on 2023-11-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                default="user@user.com", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
